name: kitchen_manager

services:
  app:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    env_file: ../.env
    volumes:
      - ./data:/data
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.kitchen.rule=Host(`myinisjap.tplinkdns.com`) && PathPrefix(`/kitchen-manager`)
      - traefik.http.routers.kitchen.entrypoints=websecure
      - traefik.http.routers.kitchen.tls.certresolver=le
      - traefik.http.services.kitchen.loadbalancer.server.port=8080
      - traefik.http.middlewares.kitchen-strip.stripprefix.prefixes=/kitchen-manager
      - traefik.http.routers.kitchen.middlewares=forward-auth,kitchen-strip
    networks:
      - proxy_net
      - default

  splash:
    image: scrapinghub/splash
    restart: unless-stopped

networks:
  proxy_net:
    external: true
